name: app
type: 'php:7.2'

web:
  locations:
    '/':
      root: 'web'
      index: ['index.php']

disk: 512

hooks:
    build: |
      set -e
      if ! command -v platform >/dev/null; then
        curl -sS https://platform.sh/cli/installer | php
      fi

crons:
  # Automatically redeploy every month to refresh LE certificates.
  redeploy:
    spec: '0 0 1 * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        platform redeploy --yes --no-wait
      fi
